### ISSUE TITLE
Import Error: python no module named pil

### ISSUE THREAD

**Issue by PikabobAlex** [onepill/texture_unpacker_scirpt#13]
為什麼會我跑python no module named pil 的東西出來呢？
我已經安裝Pillow 了

**Comment by onepill** [comment]
你好，不好意思，才看到消息。我这边没有能重现你描述的问题。方便贴一下
```
pip freeze
```
输出的结果吗？

**Comment by PikabobAlex** [comment]
啊，不好意思，我忘了告诉你已经okay了。原来是我没有update pip和没有正确安装pillow。现在已经okay了。謝謝你的program啊。感恩感恩

**Comment by onepill** [comment]
不用客气哈
